services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./RickAndMortyClient/backend
    env_file:
      - .env
    volumes:
      - ./RickAndMortyClient/backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    working_dir: /code
    command: >
      bash -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:

